name: 'get & cache Deps'
description: 'get & cache Deps desca'
inputs:
  cache:
    description: '0 or 1'
    retuqired: false
    default: 'true'
outputs:
  used-cache:
    description: '0 or 1'
    value: ${{ steps.install.outputs.cache }}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: inputs.cache == 'true'
      id: cache
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || inputs.cache != 'true'
      id: install
      run: |
        npm ci
        echo "::set-ouput name=cache::'${{ inputs.cache}}'"
      shell: bash
